import io
import sys
import json
import os
import logging
import warnings
from contextlib import redirect_stderr
from dataclasses import dataclass
from typing import Optional

from anthropic import Anthropic

from .models import ProtocolSchema
from .config import ConfigLoader

# Suppress opentrons simulator warnings
logging.getLogger("opentrons").setLevel(logging.ERROR)
warnings.filterwarnings("ignore", module="opentrons")


LINE_WIDTH = 60  # Same as the ===== separator

from . import colors as C

def _log(msg: str = ""):
    """Print progress/status to stderr (keeps stdout clean for data output)."""
    print(msg, file=sys.stderr)


def _wrap(text: str, indent: str = "  ", width: int = LINE_WIDTH) -> str:
    """Wrap text to fit within LINE_WIDTH, preserving the indent."""
    import textwrap
    return textwrap.fill(text, width=width, initial_indent=indent,
                         subsequent_indent=indent)


def _stage(label: str):
    """Print a stage header with visual separation."""
    _log()
    _log(C.separator(LINE_WIDTH))
    _log(C.header(label))


from opentrons import simulate


@dataclass
class PipelineResult:
    """Result from a successful protocol generation pipeline run."""
    script: str
    simulation_log: str
    protocol_schema: ProtocolSchema
    runlog: list
    config: dict


def generate_python_script(protocol: ProtocolSchema) -> str:
    """Generates a valid Opentrons Python script from the Pydantic schema.
    the pydantic schema is generated by the llm, given the natural language.
    this converts nl to script
    """

    lines = [
        "from opentrons import protocol_api",
        "",
        f"metadata = {{'protocolName': '{protocol.protocol_name}', 'author': '{protocol.author}', 'apiLevel': '2.15'}}",
        "",
        "def run(protocol: protocol_api.ProtocolContext):",
    ]

    # Protocol has objects and actions: labware, pipettes, modules, and commands
    # Order matters: Modules first, then labware (some may load onto modules), then pipettes

    # Load Modules first (labware may need to load onto them)
    module_map = {}
    if protocol.modules:
        for mod in protocol.modules:
            var_name = f"mod_{mod.slot.replace('-', '_')}"
            module_type_map = {
                "temperature": "temperature module gen2",
                "magnetic": "magnetic module gen2",
                "heater_shaker": "heaterShakerModuleV1",
                "thermocycler": "thermocyclerModuleV2",
            }
            api_name = module_type_map.get(mod.module_type, mod.module_type)
            lines.append(f"    {var_name} = protocol.load_module('{api_name}', '{mod.slot}')")
            module_map[mod.slot] = var_name
            if mod.label:
                module_map[mod.label] = var_name
        lines.append("")

    # Load Labware (either directly on deck or onto modules)
    labware_map = {}
    for lw in protocol.labware:
        var_name = f"lw_{lw.slot}"
        label_arg = f", label='{lw.label}'" if lw.label else ""

        if lw.on_module:
            # Load labware onto a module
            mod_var = module_map.get(lw.on_module)
            if not mod_var:
                raise ValueError(f"Module '{lw.on_module}' not found for labware '{lw.label or lw.slot}'")
            lines.append(f"    {var_name} = {mod_var}.load_labware('{lw.load_name}'{label_arg})")
        else:
            # Load labware directly on deck slot
            lines.append(f"    {var_name} = protocol.load_labware('{lw.load_name}', '{lw.slot}'{label_arg})")

        labware_map[lw.slot] = var_name
        if lw.label:
            labware_map[lw.label] = var_name
    lines.append("")

    # Load Pipettes
    for pip in protocol.pipettes:
        tiprack_vars = [labware_map.get(tr) for tr in pip.tipracks if labware_map.get(tr)]
        tiprack_str = f", tip_racks=[{', '.join(tiprack_vars)}]" if tiprack_vars else ""
        lines.append(f"    pip_{pip.mount} = protocol.load_instrument('{pip.model}', '{pip.mount}'{tiprack_str})")
    lines.append("")

    # Execute Commands
    for cmd in protocol.commands:
        pip = f"pip_{cmd.pipette}"

        if cmd.command_type == "aspirate":
            lw = labware_map.get(cmd.labware)
            if not lw:
                raise ValueError(f"Labware '{cmd.labware}' not found")
            lines.append(f"    {pip}.aspirate({cmd.volume}, {lw}['{cmd.well}'])")

        elif cmd.command_type == "dispense":
            lw = labware_map.get(cmd.labware)
            if not lw:
                raise ValueError(f"Labware '{cmd.labware}' not found")
            lines.append(f"    {pip}.dispense({cmd.volume}, {lw}['{cmd.well}'])")

        elif cmd.command_type == "mix":
            lw = labware_map.get(cmd.labware)
            if not lw:
                raise ValueError(f"Labware '{cmd.labware}' not found")
            lines.append(f"    {pip}.mix({cmd.repetitions}, {cmd.volume}, {lw}['{cmd.well}'])")

        elif cmd.command_type == "blow_out":
            if cmd.labware and cmd.well:
                lw = labware_map.get(cmd.labware)
                if not lw:
                    raise ValueError(f"Labware '{cmd.labware}' not found")
                lines.append(f"    {pip}.blow_out({lw}['{cmd.well}'])")
            else:
                lines.append(f"    {pip}.blow_out()")

        elif cmd.command_type == "touch_tip":
            lw = labware_map.get(cmd.labware)
            if not lw:
                raise ValueError(f"Labware '{cmd.labware}' not found")
            lines.append(f"    {pip}.touch_tip({lw}['{cmd.well}'])")

        elif cmd.command_type == "air_gap":
            lines.append(f"    {pip}.air_gap({cmd.volume})")

        elif cmd.command_type == "pick_up_tip":
            if cmd.labware and cmd.well:
                lw = labware_map.get(cmd.labware)
                if not lw:
                    raise ValueError(f"Labware '{cmd.labware}' not found")
                lines.append(f"    {pip}.pick_up_tip({lw}['{cmd.well}'])")
            else:
                lines.append(f"    {pip}.pick_up_tip()")

        elif cmd.command_type == "drop_tip":
            if cmd.labware and cmd.well:
                lw = labware_map.get(cmd.labware)
                if not lw:
                    raise ValueError(f"Labware '{cmd.labware}' not found")
                lines.append(f"    {pip}.drop_tip({lw}['{cmd.well}'])")
            else:
                lines.append(f"    {pip}.drop_tip()")

        elif cmd.command_type == "return_tip":
            lines.append(f"    {pip}.return_tip()")

        # Flow control commands
        elif cmd.command_type == "pause":
            # Escape single quotes in message
            msg = cmd.message.replace("'", "\\'")
            lines.append(f"    protocol.pause('{msg}')")

        elif cmd.command_type == "delay":
            if cmd.minutes:
                lines.append(f"    protocol.delay(minutes={cmd.minutes})")
            elif cmd.seconds:
                lines.append(f"    protocol.delay(seconds={cmd.seconds})")

        elif cmd.command_type == "comment":
            # Escape single quotes in message
            msg = cmd.message.replace("'", "\\'")
            lines.append(f"    protocol.comment('{msg}')")

        elif cmd.command_type == "transfer":
            src_lw = labware_map.get(cmd.source_labware)
            dst_lw = labware_map.get(cmd.dest_labware)
            if not src_lw or not dst_lw:
                raise ValueError(f"Labware '{cmd.source_labware}' or '{cmd.dest_labware}' not found")

            args = [
                str(cmd.volume),
                f"{src_lw}['{cmd.source_well}']",
                f"{dst_lw}['{cmd.dest_well}']",
            ]
            kwargs = []
            if cmd.new_tip != "always":
                kwargs.append(f"new_tip='{cmd.new_tip}'")
            if cmd.mix_before:
                # Ensure tuple format (reps, volume) for Opentrons API
                kwargs.append(f"mix_before=({cmd.mix_before[0]}, {cmd.mix_before[1]})")
            if cmd.mix_after:
                # Ensure tuple format (reps, volume) for Opentrons API
                kwargs.append(f"mix_after=({cmd.mix_after[0]}, {cmd.mix_after[1]})")

            all_args = ", ".join(args + kwargs)
            lines.append(f"    {pip}.transfer({all_args})")

        elif cmd.command_type == "distribute":
            src_lw = labware_map.get(cmd.source_labware)
            dst_lw = labware_map.get(cmd.dest_labware)
            if not src_lw or not dst_lw:
                raise ValueError(f"Labware '{cmd.source_labware}' or '{cmd.dest_labware}' not found")

            dest_wells_str = ", ".join([f"{dst_lw}['{w}']" for w in cmd.dest_wells])
            args = [
                str(cmd.volume),
                f"{src_lw}['{cmd.source_well}']",
                f"[{dest_wells_str}]",
            ]
            kwargs = []
            if cmd.new_tip != "once":
                kwargs.append(f"new_tip='{cmd.new_tip}'")

            all_args = ", ".join(args + kwargs)
            lines.append(f"    {pip}.distribute({all_args})")

        elif cmd.command_type == "consolidate":
            src_lw = labware_map.get(cmd.source_labware)
            dst_lw = labware_map.get(cmd.dest_labware)
            if not src_lw or not dst_lw:
                raise ValueError(f"Labware '{cmd.source_labware}' or '{cmd.dest_labware}' not found")

            source_wells_str = ", ".join([f"{src_lw}['{w}']" for w in cmd.source_wells])
            args = [
                str(cmd.volume),
                f"[{source_wells_str}]",
                f"{dst_lw}['{cmd.dest_well}']",
            ]
            kwargs = []
            if cmd.new_tip != "once":
                kwargs.append(f"new_tip='{cmd.new_tip}'")

            all_args = ", ".join(args + kwargs)
            lines.append(f"    {pip}.consolidate({all_args})")

        # Module commands
        elif cmd.command_type == "set_temperature":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.set_temperature({cmd.celsius})")

        elif cmd.command_type == "wait_for_temperature":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.await_temperature({cmd.celsius})")

        elif cmd.command_type == "deactivate":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.deactivate()")

        elif cmd.command_type == "engage_magnets":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            if cmd.height:
                lines.append(f"    {mod}.engage(height_from_base={cmd.height})")
            else:
                lines.append(f"    {mod}.engage()")

        elif cmd.command_type == "disengage_magnets":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.disengage()")

        elif cmd.command_type == "set_shake_speed":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            if cmd.rpm == 0:
                lines.append(f"    {mod}.stop_shaking()")
            else:
                lines.append(f"    {mod}.set_and_wait_for_shake_speed({cmd.rpm})")

        elif cmd.command_type == "open_latch":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.open_labware_latch()")

        elif cmd.command_type == "close_latch":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.close_labware_latch()")

        elif cmd.command_type == "open_lid":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.open_lid()")

        elif cmd.command_type == "close_lid":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.close_lid()")

        elif cmd.command_type == "set_block_temperature":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            args = [str(cmd.celsius)]
            if cmd.hold_time_seconds:
                args.append(f"hold_time_seconds={cmd.hold_time_seconds}")
            if cmd.hold_time_minutes:
                args.append(f"hold_time_minutes={cmd.hold_time_minutes}")
            lines.append(f"    {mod}.set_block_temperature({', '.join(args)})")

        elif cmd.command_type == "set_lid_temperature":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            lines.append(f"    {mod}.set_lid_temperature({cmd.celsius})")

        elif cmd.command_type == "run_profile":
            mod = module_map.get(cmd.module)
            if not mod:
                raise ValueError(f"Module '{cmd.module}' not found")
            steps_str = str(cmd.steps)
            lines.append(f"    {mod}.execute_profile(steps={steps_str}, repetitions={cmd.repetitions})")

        else:
            raise ValueError(f"Unknown command type: {cmd.command_type}")

    return "\n".join(lines)


def simulate_script(script_code: str) -> tuple[bool, str, list]:
    """Runs the script through the Opentrons simulator.

    Returns:
        Tuple of (success, formatted_log, raw_runlog)
        - success: True if simulation passed
        - formatted_log: Human-readable simulation log or error message
        - raw_runlog: List of command dicts from simulator (empty on failure)
    """
    protocol_file = io.StringIO(script_code)
    try:
        # Suppress simulator stderr output (deck calibration warnings, etc.)
        stderr_capture = io.StringIO()
        with redirect_stderr(stderr_capture):
            runlog, _ = simulate.simulate(protocol_file)
        # Format the run log into readable output
        log_lines = ["Simulation completed successfully.", "", "Run Log:"]
        for entry in runlog:
            if isinstance(entry, dict):
                msg = entry.get('payload', {}).get('text', str(entry))
                log_lines.append(f"  {msg}")
            else:
                log_lines.append(f"  {entry}")
        return True, "\n".join(log_lines), runlog
    except Exception as e:
        return False, f"Simulation failed: {str(e)}", []


class ProtocolAgent:
    def __init__(self, config_path: str = "lab_config.json",
                 confirmation_manager=None,
                 reporter=None):
        """
        Args:
            config_path: path to lab_config.json
            confirmation_manager: optional ConfirmationManager (see
                nl2protocol.confirmation). Defaults to InteractiveCM, which
                preserves the existing CLI behavior. Tests and evals can pass
                ScriptedCM(answers) or AutoConfirmCM() to drive the pipeline
                non-interactively.
            reporter: optional Reporter (see nl2protocol.reporting). Defaults
                to ConsoleReporter, which preserves the existing CLI banners.
                Tests pass CapturingReporter to inspect the structured event
                stream without I/O. Future HTML/TUI sinks plug in here.
        """
        from nl2protocol.confirmation import InteractiveCM
        from nl2protocol.reporting import ConsoleReporter
        self.config_path = config_path
        self.config_loader = ConfigLoader(config_path=config_path)
        self.cm = confirmation_manager or InteractiveCM()
        self.reporter = reporter or ConsoleReporter()

    @staticmethod
    def _infer_source_containers(spec) -> list:
        """Identify labware wells that are only aspirated from, never dispensed into.

        These are source containers (reservoirs, tube racks) that the scientist
        fills before running the protocol. Returns list of (labware, well, substance).
        """
        # Track which wells are sources vs destinations
        source_wells = {}   # (labware, well) → substance
        dest_wells = set()  # (labware, well)

        liquid_actions = {"transfer", "distribute", "consolidate",
                          "serial_dilution", "aspirate"}

        for step in spec.steps:
            if step.action not in liquid_actions:
                continue

            # Source side
            if step.source:
                desc = step.source.description
                wells = []
                if step.source.well:
                    wells = [step.source.well]
                elif step.source.wells:
                    wells = step.source.wells
                for w in wells:
                    key = (desc, w)
                    if key not in source_wells:
                        source_wells[key] = step.substance.value if step.substance else None

            # Destination side
            if step.destination:
                desc = step.destination.description
                wells = []
                if step.destination.well:
                    wells = [step.destination.well]
                elif step.destination.wells:
                    wells = step.destination.wells
                # For well ranges, just mark the description as having destinations
                if step.destination.well_range:
                    dest_wells.add((desc, "__range__"))
                for w in wells:
                    dest_wells.add((desc, w))

        # Source-only wells: aspirated from but never dispensed into
        # Also exclude wells whose labware appears as a destination anywhere
        #  (e.g., serial dilution where the same plate is both source and dest)
        dest_labware = {lw for lw, _ in dest_wells}
        already_tracked = {(ic.labware, ic.well) for ic in spec.initial_contents}

        results = []
        seen = set()
        for (labware, well), substance in source_wells.items():
            if labware in dest_labware:
                continue  # Same labware used as dest elsewhere — not a pure source
            if (labware, well) in already_tracked:
                continue  # Already in initial_contents from LLM extraction
            if (labware, well) in seen:
                continue
            seen.add((labware, well))
            results.append((labware, well, substance))

        return results

    def _confirm_labware_assignments(self, spec) -> Optional[dict]:
        """Interactive confirmation of labware description → config label assignments.

        Shows all assignments at once. User picks a number to change any mapping,
        or presses Enter to confirm all. Unresolved refs show as '???' and must
        be assigned before confirming.

        Returns dict of {description: confirmed_label} or None if aborted.
        """
        # Collect unique (description, resolved_label) pairs
        assignments = []
        seen = set()
        for step in spec.steps:
            for ref in [step.source, step.destination]:
                if ref and ref.description not in seen:
                    seen.add(ref.description)
                    assignments.append({
                        "description": ref.description,
                        "resolved_label": ref.resolved_label,
                    })

        if not assignments:
            return {}

        available_labels = list(self.config_loader.config.get("labware", {}).keys())
        # Start with LLM suggestions as current assignments
        current = {a["description"]: a["resolved_label"] for a in assignments}

        while True:
            # Display all assignments
            _log(f"\n  {C.label('Labware assignments')}:")
            all_resolved = True
            for i, a in enumerate(assignments, 1):
                desc = a["description"]
                label = current.get(desc)
                if label:
                    load_name = self.config_loader.config["labware"][label].get("load_name", "")
                    _log(f"    [{i}] \"{desc}\" → {C.success(label)} ({C.dim(load_name)})")
                else:
                    _log(f"    [{i}] \"{desc}\" → {C.warning('??? (no match)')}")
                    all_resolved = False

            # Prompt
            if all_resolved:
                response = self.cm.prompt("Pick a number to change, or Enter to confirm all (q=quit): ").lower()
            else:
                _log(f"  {C.dim('Assign all ??? items before confirming. If your config is missing')}")
                _log(f"  {C.dim('labware, quit (q) and add it to your config.json, then re-run.')}")
                response = self.cm.prompt("Pick a number to assign (q=quit): ").lower()

            if response == 'q':
                _log("  Aborted.")
                return None
            elif response == '':
                if all_resolved:
                    # Warn if multiple descriptions map to the same label
                    label_counts = {}
                    for desc, label in current.items():
                        label_counts.setdefault(label, []).append(desc)
                    for label, descs in label_counts.items():
                        if len(descs) > 1:
                            _log(f"  {C.warning('Note:')} \"{descs[0]}\" and \"{descs[1]}\" "
                                 f"both map to {label} — is this the same labware?")
                    return current
                else:
                    unresolved = [a["description"] for a in assignments if not current.get(a["description"])]
                    _log(f"  Cannot confirm — unresolved: {unresolved}")
                    continue
            elif response.isdigit():
                idx = int(response) - 1
                if 0 <= idx < len(assignments):
                    desc = assignments[idx]["description"]
                    _log(f"\n    Reassigning \"{desc}\":")
                    for j, label in enumerate(available_labels, 1):
                        load_name = self.config_loader.config["labware"][label].get("load_name", "")
                        marker = " ←" if label == current.get(desc) else ""
                        _log(f"      {j}. {label} ({C.dim(load_name)}){marker}")
                    pick = self.cm.prompt(f"Pick label (1-{len(available_labels)}), or Enter to cancel: ")
                    if pick.isdigit():
                        pick_idx = int(pick) - 1
                        if 0 <= pick_idx < len(available_labels):
                            current[desc] = available_labels[pick_idx]
                        else:
                            _log(f"    Invalid number.")
                    elif pick == '':
                        pass  # cancelled
                    else:
                        _log(f"    Invalid input.")
                else:
                    _log(f"  Invalid number. Pick 1-{len(assignments)}.")
            else:
                _log(f"  Invalid input. Pick a number, Enter, or q.")

    def run_pipeline(self, prompt: str, csv_path: str = None,
                     full_confirmation: bool = False, confirmation_threshold: float = 0.7,
                     verbose: bool = False) -> Optional[PipelineResult]:
        """Run the protocol generation pipeline.

        New architecture (v2):
          Stage 0: Input validation
          Stage 1: LLM reasons through instruction → ProtocolSpec (one LLM call)
          Stage 2: Hallucination guard + sufficiency check + gap filling
          Stage 3: User confirms the spec
          Stage 4: Deterministic: spec + config → ProtocolSchema (no LLM)
          Stage 5: Deterministic: ProtocolSchema → Python script (no LLM)
          Stage 6: Opentrons simulation
          Stage 7: Intent verification (LLM, optional safety net)

        Only Stage 1 uses an LLM for generation. Stages 4-5 are deterministic,
        so user-specified volumes can never be corrupted.

        Falls back to the old LLM-based generation if the deterministic path fails.
        """
        from datetime import datetime
        from .extraction import SemanticExtractor
        from .reporting import StageEvent

        # Emit raw instruction event for downstream reporters (HTMLReporter etc.)
        self.reporter.emit(StageEvent(
            kind="raw_instruction",
            data={"instruction": prompt},
            stage_name="input",
        ))

        # DEV ONLY — remove before public release.
        # Intermediate state log: accumulates spec snapshots throughout the
        # pipeline, written to disk on completion or failure for inspection.
        output_dir = "output"
        os.makedirs(output_dir, exist_ok=True)

        state_log = {
            "timestamp": datetime.now().isoformat(),
            "input": {"instruction": prompt},
        }

        def _save_state_log(failed_at: str = None):
            if failed_at:
                state_log["failed_at"] = failed_at
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            path = os.path.join(output_dir, f"pipeline_state_{ts}.json")
            with open(path, 'w') as f:
                json.dump(state_log, f, indent=2, default=str)
            _log(f"  {C.dim(f'State log: {path}')}")

        # Stage 1: Validate config and instruction
        _stage("[Stage 1/8] Validating instruction and config...")
        try:
            self.config_loader.load_config()
            state_log["input"]["config"] = self.config_loader.config
            _log(f"  {C.success('Config validated.')}")
        except Exception as e:
            _log(f"  {C.error('Config validation failed:')}")
            _log(f"    {e}")
            _save_state_log("stage_1_config")
            return None

        
        from .validation.input_validator import InputValidator
        validator = InputValidator()
        try:
            validation = validator.classify(prompt)
        except Exception as e:
            _log(f"  {C.error(str(e))}")
            return None

        if not validation.is_valid_protocol:
            if validation.classification == "QUESTION":
                _log("  This looks like a question, not a protocol instruction.")
                _log("  Try rephrasing as an action: 'Transfer 100uL from A1 to B1'")
            elif validation.classification == "AMBIGUOUS":
                _log("  This instruction is too vague to generate a protocol.")
                _log("  Try adding specific volumes, wells, and labware names.")
            elif validation.classification == "INVALID":
                _log("  This doesn't appear to be a liquid-handling protocol.")
                _log("  The OT-2 can only pipette — it can't centrifuge, read absorbance, etc.")
            if validation.suggestion:
                _log(f"  Suggestion: {validation.suggestion}")
            return None
        _log(f"  {C.success('Input validated as protocol instruction.')}")
        

        # Stage 2: Reason through the instruction → ProtocolSpec
        _stage("[Stage 2/8] Reasoning through protocol instruction...")
        extractor = SemanticExtractor(
            client=self.config_loader.client,
            model_name=self.config_loader.model_name
        )
        spec = extractor.extract(prompt, self.config_loader.config)

        if spec is not None:
            # Emit extracted spec event for downstream reporters.
            self.reporter.emit(StageEvent(
                kind="extracted_spec",
                data={"spec": spec},
                stage_name="stage_2_extraction",
            ))

        if spec is None:
            _log("\n  Could not extract a protocol from your instruction.")
            _log("  This can happen if:")
            _log("    - The instruction is too vague (add volumes, wells, labware names)")
            _log("    - The API key is invalid or out of credits")
            _log("    - The instruction isn't about liquid handling")
            _log("  Try: 'Transfer 100uL from source_plate A1 to dest_plate B1'")
            _save_state_log("stage_2_extraction")
            return None

        state_log["stage_2_extraction"] = spec.model_dump()

        _log(f"  {C.label('Protocol type:')} {spec.protocol_type or 'ad-hoc'}")
        _log(f"  {C.label('Steps:')} {len(spec.steps)}")
        if spec.reasoning:
            _log(f"  {C.label('Reasoning:')}")
            import re
            reasoning = spec.reasoning.strip()
            parts = re.split(r'(?=\d+\.\s)', reasoning)
            for part in parts:
                part = part.strip()
                if not part:
                    continue
                sub_parts = re.split(r'(?=\s*-\s)', part, maxsplit=0)
                for i, sub in enumerate(sub_parts):
                    sub = sub.strip()
                    if not sub:
                        continue
                    if i == 0:
                        _log(_wrap(C.info(sub), indent="    ", width=LINE_WIDTH))
                    else:
                        _log(_wrap(C.info(f"- {sub.lstrip('- ')}"), indent="      ", width=LINE_WIDTH))

        if spec.initial_contents:
            _log(f"  {C.dim(f'Initial state: {len(spec.initial_contents)} wells/tubes have contents')}")

        # Stage 3: Validate extraction + check sufficiency + fill gaps
        _stage("[Stage 3/8] Validating and completing specification...")

        # Stage 3: unified gap-resolution orchestrator (ADR-0008).
        # PR3b deleted the legacy verify/fill/refine block and the use_gap_resolver
        # flag — see ADR-0008's "what we replaced" appendix for the legacy → new
        # mapping. The orchestrator handles missing fields, fabrications, initial
        # volumes, constraint violations, and labware ambiguity in one loop.
        from .gap_resolution import (
            Orchestrator, CLIConfirmationHandler, default_apply_resolution,
            MissingFieldsDetector, ProvenanceWarningDetector,
            InitialContentsVolumeDetector, ConstraintViolationDetector,
            LabwareAmbiguityDetector,
            ConfigLookupSuggester, CarryoverSuggester,
            WellCapacitySuggester, RegexFromNoteSuggester,
            WellRangeClipSuggester, LabwareSuggester, LLMSpotSuggester,
            IndependentReviewSuggester,
        )

        # Run LabwareResolver BEFORE the orchestrator so LabwareAmbiguityDetector
        # only flags refs the resolver couldn't pick (post-resolver state). The
        # resolver writes resolved_label_provenance on each pick so the
        # IndependentReviewSuggester can second-opinion the choice. Stage 3.5
        # no longer runs the resolver — it's done here.
        from .extraction import LabwareResolver as _EarlyLabwareResolver
        spec = _EarlyLabwareResolver(
            config=self.config_loader.config,
            client=extractor.client,
            model_name=extractor.model_name,
        ).resolve(spec)

        # ADR-0011 Phase 1: emit labware_resolution_done so column 4
        # (validated spec) can populate with the description→label
        # mapping when rendered.
        self.reporter.emit(StageEvent(
            kind="labware_resolution_done",
            data={
                "resolutions": {
                    ref.description: ref.resolved_label
                    for step in spec.steps
                    for ref in [step.source, step.destination]
                    if ref and ref.resolved_label
                },
            },
            stage_name="stage_3_labware_resolver",
        ))

        # Reviewer: smaller / different model than the extractor's per ADR-0008's
        # bias-mitigation rationale. Haiku is cheap, fast, and sufficient for
        # the structured two-claim verification task.
        reviewer_model = "claude-haiku-4-5"
        orch = Orchestrator(
            detectors=[
                MissingFieldsDetector(),
                ProvenanceWarningDetector(extractor),  # only fabrications surface as Gaps
                InitialContentsVolumeDetector(),
                ConstraintViolationDetector(),
                LabwareAmbiguityDetector(),
            ],
            suggesters=[
                # Deterministic first (correct-or-empty, no LLM cost):
                ConfigLookupSuggester(),
                CarryoverSuggester(),
                WellCapacitySuggester(),
                RegexFromNoteSuggester(),
                WellRangeClipSuggester(),
                LabwareSuggester(),
                # LLM spot last — bounded per-Gap call before falling through
                # to the user. Replaces the old wholesale `refine`.
                LLMSpotSuggester(client=extractor.client,
                                  model_name=extractor.model_name),
            ],
            reviewer=IndependentReviewSuggester(
                client=extractor.client,
                model_name=reviewer_model,
            ),
            handler=CLIConfirmationHandler(cm=self.cm, log=_log),
            apply_resolution=default_apply_resolution,
            # ADR-0011 Phase 1: orchestrator emits storytelling events
            # (gap_iteration_*, gap_detected, gap_resolved) into the same
            # reporter that handles stage events.
            reporter=self.reporter,
        )
        outcome = orch.run(spec, context={
            "instruction": prompt,
            "config": self.config_loader.config,
        })
        state_log["stage_3_gap_resolver"] = {
            "converged": outcome.converged,
            "aborted": outcome.aborted,
            "iterations": [
                {
                    "iteration": it.iteration,
                    "gap_count": len(it.records),
                    "auto_accepted": sum(1 for r in it.records if r.auto_accepted),
                }
                for it in outcome.iterations
            ],
        }
        if outcome.aborted:
            _log(f"  {C.error('Gap resolution aborted.')}")
            _save_state_log("stage_3_gap_resolver")
            return None
        if not outcome.converged:
            _log(f"  {C.error('Gap resolution hit iteration cap without converging.')}")
            _save_state_log("stage_3_gap_resolver")
            return None
        _log(f"  {C.success('Gap resolution converged.')}")
        spec = outcome.spec

        if spec.explicit_volumes:
            _log(f"  {C.dim(f'Locked volumes: {spec.explicit_volumes}')}")

        # Infer source containers: labware that is aspirated from but never
        # dispensed into must be pre-filled by the scientist.
        source_only = self._infer_source_containers(spec)
        if source_only:
            _log("\n  Inferred source containers (pre-filled by you before running):")
            for labware, well, substance in source_only:
                sub = f" ({substance})" if substance else ""
                _log(f"    - {labware} well {well}{sub}")
            if sys.stdin.isatty():
                response = self.cm.prompt("Is this correct? [Y/n]: ").lower()
                if response in ('n', 'no'):
                    _log("  Aborted. Adjust your instruction to clarify source containers.")
                    state_log["stage_3_sources"] = [{"labware": lw, "well": w, "substance": s} for lw, w, s in source_only]
                    _save_state_log("stage_3_sources")
                    return None
            # Add confirmed sources to initial_contents so well tracker doesn't warn
            from .extraction import WellContents
            for labware, well, substance in source_only:
                already = any(ic.labware == labware and ic.well == well
                              for ic in spec.initial_contents)
                if not already:
                    spec.initial_contents.append(
                        WellContents(labware=labware, well=well,
                                     substance=substance or "reagent")
                    )

        # Stage 3.5: Confirm labware assignments + check unresolved refs
        # (resolver already ran inside stage 3 before the orchestrator —
        # PR3b removed the redundant second resolve call).
        _stage("[Stage 3.5/8] Confirming labware assignments...")

        state_log["stage_3.5_resolution"] = {
            ref.description: ref.resolved_label
            for step in spec.steps
            for ref in [step.source, step.destination]
            if ref
        }

        # Confirm tentative assignments with user (includes unresolved refs)
        if sys.stdin.isatty():
            confirmed = self._confirm_labware_assignments(spec)
            if confirmed is None:
                _save_state_log("stage_3.5_resolution")
                return None
            for step in spec.steps:
                for ref in [step.source, step.destination]:
                    if ref and ref.description in confirmed:
                        ref.resolved_label = confirmed[ref.description]

        # Check if any step LocationRef is still unresolved — that's a hard error.
        unresolved_refs = []
        for step in spec.steps:
            for ref in [step.source, step.destination]:
                if ref and not ref.resolved_label and ref.description not in unresolved_refs:
                    unresolved_refs.append(ref.description)

        if unresolved_refs:
            _log(f"\n  {C.error('No config match for:')} {unresolved_refs}")
            _log(f"  Add appropriate labware to your config.json for these, then re-run.")
            _save_state_log("stage_3.5_unresolved")
            return None

        _log(f"  {C.success('All labware resolved.')}")

        # Stage 4: Constraint checking (deterministic, no LLM)
        _stage("[Stage 4/8] Checking hardware constraints...")
        from .validation.constraints import ConstraintChecker
        checker = ConstraintChecker(self.config_loader.config)
        constraint_result = checker.check_all(spec)

        state_log["stage_4_constraints"] = {
            "errors": [str(v) for v in constraint_result.errors],
            "warnings": [str(w) for w in constraint_result.warnings],
        }

        # ADR-0011 Phase 1: emit constraint_check_done so column 4
        # (validated spec) can show whether the spec passed constraint
        # checks cleanly. Most ERROR violations should already be 0
        # (orchestrator's ConstraintViolationDetector resolved them);
        # this event captures the residual + any WARNING-severity items.
        self.reporter.emit(StageEvent(
            kind="constraint_check_done",
            data={
                "violation_count": len(constraint_result.errors),
                "warnings": [str(w) for w in constraint_result.warnings],
            },
            stage_name="stage_4_constraints",
        ))

        if constraint_result.warnings:
            for w in constraint_result.warnings:
                _log(f"  {w}")

        if constraint_result.has_errors:
            _log(f"\n  {C.error('HARDWARE CONFLICTS DETECTED')} ({len(constraint_result.errors)}):")
            _log("  " + "-" * 56)
            for v in constraint_result.errors:
                _log(f"  {v}")
                _log()

            if sys.stdin.isatty():
                _log("  These conflicts mean the protocol may not execute correctly.")
                response = self.cm.prompt("Proceed anyway? [y/N]: ").lower()
                if response not in ('y', 'yes'):
                    _log("  Aborted. Fix your config or instruction and retry.")
                    _save_state_log("stage_4_constraints")
                    return None
                _log(f"  {C.dim('Proceeding with constraint adjustments.')}")
            else:
                _log("  Cannot proceed with hardware conflicts in non-interactive mode.")
                _save_state_log("stage_4_constraints")
                return None
        else:
            _log(f"  {C.success('All constraints satisfied.')}")

        # PR3b removed the pre-stage-5 confirmation queue. The orchestrator
        # in stage 3 already routed every confirmable through CLIConfirmationHandler
        # (initial volumes via InitialContentsVolumeDetector, provenance warnings
        # via ProvenanceWarningDetector, etc.). No bulk-print pass needed; the
        # HTML report (ADR-0009) replaces it for visual review.

        # Stage 5: Deterministic spec → ProtocolSchema
        _stage("[Stage 5/8] Converting specification to protocol schema...")

        state_log["stage_5_spec"] = spec.model_dump()

        try:
            from .extraction import CompleteProtocolSpec
            complete_spec = CompleteProtocolSpec.model_validate(spec.model_dump())
            # Emit completed spec event for downstream reporters.
            self.reporter.emit(StageEvent(
                kind="completed_spec",
                data={"spec": complete_spec},
                stage_name="stage_5_spec",
            ))
            protocol_schema, well_state_warnings, step_summaries = extractor.spec_to_schema(
                complete_spec, self.config_loader.config)
            _log(f"  {C.dim('Schema generated.')}")
        except Exception as e:
            err = str(e)
            _log(f"  Schema conversion failed.")
            if "not found" in err.lower():
                _log(f"    A labware or module reference could not be resolved: {err}")
                _log(f"    Check that your config labels match the specification above.")
            else:
                _log(f"    Detail: {err}")
            _log(f"    This is a deterministic step — the specification likely has an inconsistency.")
            _save_state_log("stage_5_schema")
            return None

        # Stage 6: Deterministic schema → Python script
        _stage("[Stage 6/8] Generating Python script...")
        try:
            script = generate_python_script(protocol_schema)
            _log(f"  {C.dim('Script generated.')}")
            # Emit generated script event for downstream reporters.
            self.reporter.emit(StageEvent(
                kind="generated_script",
                data={"script": script},
                stage_name="stage_6_script",
            ))
        except ValueError as e:
            err = str(e)
            _log(f"  Script generation failed.")
            _log(f"    Detail: {err}")
            _log(f"    Try: simplify your instruction or check config slot assignments.")
            _save_state_log("stage_6_script")
            return None

        # Save script for debugging regardless of simulation outcome
        debug_script = os.path.join(output_dir, f"debug_script_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py")
        with open(debug_script, 'w') as f:
            f.write(script)
        _log(f"  {C.dim(f'Debug: script saved to {debug_script}')}")

        # Stage 7: Opentrons simulation
        _stage("[Stage 7/8] Running Opentrons simulation...")
        success, simulation_log, runlog = simulate_script(script)

        if not success:
            if "errorType=" in simulation_log:
                import re
                error_match = re.search(r"errorType='([^']+)'", simulation_log)
                error_detail_match = re.search(r"errorInfo=\{[^}]*'detail':\s*'([^']+)'", simulation_log)
                error_type = error_match.group(1) if error_match else "Unknown"
                error_detail = error_detail_match.group(1) if error_detail_match else simulation_log[:300]
                _log(f"  Simulation failed: {error_type}")
                _log(f"    Detail: {error_detail[:200]}")
            else:
                _log(f"  Simulation failed: {simulation_log[:500]}")
            _log(f"  The generated Python script did not pass the Opentrons simulator.")
            _log(f"  Check {debug_script} to see the generated code.")
            _save_state_log("stage_7_simulation")
            return None

        _log(f"  {C.success('Simulation passed.')}")

        # Pipeline complete. (Stage 8 — LLM intent verification — was removed
        # in ADR-0004; the deterministic constraint checker (Stage 4) and
        # Opentrons simulator (Stage 7) cover the load-bearing checks reliably,
        # while the intent verifier had a ~95% false-positive rate that eroded
        # user trust. See docs/adr/0004-remove-intent-verifier.md.)
        _save_state_log()
        # Flush buffered events for any reporter that batches (HTMLReporter etc.).
        # ConsoleReporter (default) is a no-op here.
        self.reporter.finalize()
        return PipelineResult(
            script=script,
            simulation_log=simulation_log,
            protocol_schema=protocol_schema,
            runlog=runlog,
            config=self.config_loader.config
        )


if __name__ == "__main__":
    import sys
    from nl2protocol.cli import main

    # If no arguments provided, show help
    if len(sys.argv) == 1:
        sys.argv.append('--help')

    sys.exit(main())
