from opentrons import protocol_api

metadata = {'protocolName': 'heat_shock_bacterial_transformation', 'author': 'Biolab AI', 'apiLevel': '2.15'}

def run(protocol: protocol_api.ProtocolContext):
    mod_3 = protocol.load_module('temperature module gen2', '3')

    lw_1 = protocol.load_labware('opentrons_96_tiprack_20ul', '1', label='tiprack_20')
    lw_2 = protocol.load_labware('opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap', '2', label='reagent_rack')
    lw_4 = protocol.load_labware('opentrons_96_tiprack_300ul', '4', label='tiprack_300')

    pip_left = protocol.load_instrument('p20_single_gen2', 'left', tip_racks=[lw_1])
    pip_right = protocol.load_instrument('p300_single_gen2', 'right', tip_racks=[lw_4])

    mod_3.set_temperature(4.0)
    mod_3.await_temperature(4.0)
    pip_left.transfer(2.0, lw_2['A1'], lw_2['B1'])
    pip_left.transfer(2.0, lw_2['A2'], lw_2['B2'])
    pip_left.transfer(2.0, lw_2['A3'], lw_2['B3'])
    pip_left.transfer(2.0, lw_2['A4'], lw_2['B4'])
    pip_left.pick_up_tip()
    pip_left.mix(3, 20.0, lw_2['B1'])
    pip_left.drop_tip()
    pip_left.pick_up_tip()
    pip_left.mix(3, 20.0, lw_2['B2'])
    pip_left.drop_tip()
    pip_left.pick_up_tip()
    pip_left.mix(3, 20.0, lw_2['B3'])
    pip_left.drop_tip()
    pip_left.pick_up_tip()
    pip_left.mix(3, 20.0, lw_2['B4'])
    pip_left.drop_tip()
    protocol.pause('incubate on ice (temp module at 4C) for 30 minutes')
    protocol.comment('Heat shock step - set temp module to 42C for exactly 45 seconds')
    mod_3.set_temperature(42.0)
    protocol.pause('user monitors heat shock timing (45 seconds)')
    mod_3.set_temperature(4.0)
    protocol.pause('incubate on ice for 2 minutes')
    pip_right.pick_up_tip()
    pip_right.transfer(200.0, lw_2['C1'], lw_2['B1'], new_tip='never')
    pip_right.transfer(200.0, lw_2['C1'], lw_2['B2'], new_tip='never')
    pip_right.transfer(200.0, lw_2['C1'], lw_2['B3'], new_tip='never')
    pip_right.transfer(200.0, lw_2['C1'], lw_2['B4'], new_tip='never')
    pip_right.drop_tip()
    pip_right.pick_up_tip()
    pip_right.mix(3, 100.0, lw_2['B1'])
    pip_right.drop_tip()
    pip_right.pick_up_tip()
    pip_right.mix(3, 100.0, lw_2['B2'])
    pip_right.drop_tip()
    pip_right.pick_up_tip()
    pip_right.mix(3, 100.0, lw_2['B3'])
    pip_right.drop_tip()
    pip_right.pick_up_tip()
    pip_right.mix(3, 100.0, lw_2['B4'])
    pip_right.drop_tip()
    protocol.pause('user transfers tubes to 37C shaker for 1 hour recovery, then plates on selective media')